import type { Title } from './types';

export const MOCK_TITLES: Title[] = [
  {
    id: 1,
    title: 'Oppenheimer',
    year: 2023,
    type: 'movie',
    rating: 8.9,
    popularity_rank: 1,
    poster_url: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    overview: 'Příběh amerického fyzika J. Roberta Oppenheimera a jeho role při vývoji atomové bomby během druhé světové války.',
    trailer_url: 'https://www.youtube.com/embed/uYPbbksJxIg',
    genres: ['Drama', 'Biografie', 'Historie'],
  },
  {
    id: 2,
    title: 'Stranger Things',
    year: 2016,
    type: 'series',
    rating: 8.7,
    popularity_rank: 2,
    poster_url: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    overview: 'Nadpřirozené záhady se odehrávají v malém městě Hawkins v Indianě, kde skupina dětí odhalí tajemství vládních experimentů.',
    trailer_url: 'https://www.youtube.com/embed/b9EkMc79ZSU',
    genres: ['Sci-Fi', 'Drama', 'Thriller'],
  },
  {
    id: 3,
    title: 'Dune: Part Two',
    year: 2024,
    type: 'movie',
    rating: 8.5,
    popularity_rank: 3,
    poster_url: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    overview: 'Paul Atreides pokračuje v cestě za pomstou za smrt své rodiny a sjednocuje Fremenské klany na planetě Arrakis.',
    trailer_url: 'https://www.youtube.com/embed/Way9Dexny3w',
    genres: ['Sci-Fi', 'Akce', 'Dobrodružství'],
  },
  {
    id: 4,
    title: 'The Last of Us',
    year: 2023,
    type: 'series',
    rating: 8.8,
    popularity_rank: 4,
    poster_url: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    overview: 'V post-apokalyptické Americe pašerák Joel provází dospívající dívku Ellie napříč Spojenými státy v naději na přežití.',
    trailer_url: 'https://www.youtube.com/embed/uLtkt8BonwM',
    genres: ['Drama', 'Akce', 'Sci-Fi'],
  },
  {
    id: 5,
    title: 'Killers of the Flower Moon',
    year: 2023,
    type: 'movie',
    rating: 7.7,
    popularity_rank: 5,
    poster_url: 'https://image.tmdb.org/t/p/w500/dB6jcBNSCEMdhQBXzWvQTHOdlNb.jpg',
    overview: 'V 20. letech 20. století série záhadných vražd otřásá národem kmene Osage v Oklahomě, což vede k jednomu z prvních vyšetřování FBI.',
    trailer_url: 'https://www.youtube.com/embed/EP34Yoxs3FQ',
    genres: ['Drama', 'Krimi', 'Historie'],
  },
  {
    id: 6,
    title: 'Wednesday',
    year: 2022,
    type: 'series',
    rating: 8.1,
    popularity_rank: 6,
    poster_url: 'https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
    overview: 'Wednesday Addams studuje na škole Nevermore Academy a snaží se ovládnout své psychické schopnosti, aby odhalila nadpřirozené záhadné vraždy.',
    trailer_url: 'https://www.youtube.com/embed/Di310WS8zLk',
    genres: ['Komedie', 'Mysterie', 'Horor'],
  },
  {
    id: 7,
    title: 'Poor Things',
    year: 2023,
    type: 'movie',
    rating: 8.0,
    popularity_rank: 7,
    poster_url: 'https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXIf52JWuciHCwI.jpg',
    overview: 'Nevěrohodný příběh Belly Baxterové, vzkříšené mrtvé ženy, která cestuje Evropou a odkrývá svět plný předsudků a osvobozující svobody.',
    trailer_url: 'https://www.youtube.com/embed/RlbR5N6veqw',
    genres: ['Komedie', 'Drama', 'Romance'],
  },
  {
    id: 8,
    title: 'Squid Game',
    year: 2021,
    type: 'series',
    rating: 8.0,
    popularity_rank: 8,
    poster_url: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    overview: 'Záhadná organizace přiláká lidi s finančními problémy do soutěže s dětskými hrami, kde výherní odměnou jsou miliardy wonů.',
    trailer_url: 'https://www.youtube.com/embed/oqxAJKy0ii4',
    genres: ['Thriller', 'Drama', 'Akce'],
  },
  {
    id: 9,
    title: 'Barbie',
    year: 2023,
    type: 'movie',
    rating: 6.9,
    popularity_rank: 9,
    poster_url: 'https://image.tmdb.org/t/p/w500/iuFNMS8vlzmfa8gSXE7kGXDO3XT.jpg',
    overview: 'Barbie a Ken zažívají existenciální krizi a vydávají se na cestu do skutečného světa, kde Barbie hledá smysl svého bytí.',
    trailer_url: 'https://www.youtube.com/embed/pBk4NYhWNMM',
    genres: ['Komedie', 'Dobrodružství', 'Fantasy'],
  },
  {
    id: 10,
    title: 'House of the Dragon',
    year: 2022,
    type: 'series',
    rating: 8.4,
    popularity_rank: 10,
    poster_url: 'https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg',
    overview: 'Prequel Hry o trůny sledující House Targaryen a válku o trůn 200 let před událostmi původní série.',
    trailer_url: 'https://www.youtube.com/embed/DotnJ7tTA34',
    genres: ['Akce', 'Dobrodružství', 'Drama'],
  },
];
